
(function () {
  let employeesData = [
    { id: "0001", name: "Anika Vaccaro", designation: "Manager", department: "Operations", team: "Super A", supervisor: "Kaylo Margo", tenure: "1 Yr, 2 Mo", profile: 95, shift: "Morning", city: "New York", salary: 85000, avatar: "https://randomuser.me/api/portraits/women/68.jpg", role: "admin" },
    { id: "0002", name: "Chance Stanton", designation: "Department Head", department: "HR", team: "Super B", supervisor: "Ayson Westervelt", tenure: "3 Yr, 6 Mo", profile: 45, shift: "Evening", city: "Austin", salary: 75000, avatar: "https://randomuser.me/api/portraits/men/32.jpg", role: "editor" },
    { id: "0003", name: "Gretchen Lubin", designation: "Team Lead", department: "Operations", team: "Super C", supervisor: "Ryan Vaccaro", tenure: "2 Yr", profile: 90, shift: "Morning", city: "Seattle", salary: 72000, avatar: "https://randomuser.me/api/portraits/women/44.jpg", role: "editor" },
    { id: "0004", name: "Roger Westervelt", designation: "VOB Specialist", department: "Operations", team: "Super D", supervisor: "Anika Gold", tenure: "1 Yr, 2 Mo", profile: 93, shift: "Night", city: "Chicago", salary: 65000, avatar: "https://randomuser.me/api/portraits/men/45.jpg", role: "viewer" },
    { id: "0005", name: "Tatiana Dias", designation: "Account Manager", department: "Operations", team: "Super E", supervisor: "Angel Levin", tenure: "1 Yr, 1 Mo", profile: 15, shift: "Morning", city: "Miami", salary: 68000, avatar: "https://randomuser.me/api/portraits/women/29.jpg", role: "viewer" },
    { id: "0006", name: "Marcus Chen", designation: "Senior Analyst", department: "Finance", team: "Alpha", supervisor: "Linda Wu", tenure: "2 Yr, 4 Mo", profile: 88, shift: "Morning", city: "San Francisco", salary: 82000, avatar: "https://randomuser.me/api/portraits/men/22.jpg", role: "editor" },
    { id: "0007", name: "Sophia Rodriguez", designation: "HR Generalist", department: "HR", team: "Talent Squad", supervisor: "Chance Stanton", tenure: "1 Yr", profile: 72, shift: "Evening", city: "Los Angeles", salary: 62000, avatar: "https://randomuser.me/api/portraits/women/90.jpg", role: "viewer" },
    { id: "0008", name: "James Okafor", designation: "IT Support", department: "Technology", team: "TechOps", supervisor: "Rita Blake", tenure: "6 Mo", profile: 60, shift: "Night", city: "Houston", salary: 58000, avatar: "https://randomuser.me/api/portraits/men/55.jpg", role: "viewer" },
    { id: "0009", name: "Elena Park", designation: "Product Owner", department: "Product", team: "Innovate", supervisor: "Marcus Chen", tenure: "8 Mo", profile: 82, shift: "Morning", city: "Seattle", salary: 90000, avatar: "https://randomuser.me/api/portraits/women/12.jpg", role: "editor" }
  ];
  let auditLog = [], currentFilters = { jobTitle: "", department: "", team: "", city: "" };
  let employeeModal = null, permissionsModal = null, isEditMode = false;

  function addLog(action, details) { auditLog.unshift({ timestamp: new Date().toLocaleString(), action, details }); if (auditLog.length > 20) auditLog.pop(); }
  function getFiltered() { return employeesData.filter(e => (!currentFilters.jobTitle || e.designation.toLowerCase().includes(currentFilters.jobTitle.toLowerCase())) && (!currentFilters.department || e.department.toLowerCase().includes(currentFilters.department.toLowerCase())) && (!currentFilters.team || e.team.toLowerCase().includes(currentFilters.team.toLowerCase())) && (!currentFilters.city || e.city.toLowerCase().includes(currentFilters.city.toLowerCase()))); }
  function profileClass(p) { return p < 40 ? "low" : p < 70 ? "medium" : "high"; }
  function renderProfile(p) { let cls = profileClass(p); return `<div class="profile-bar ${cls}"><div class="bar-fill" style="width:${p}%"></div></div><div class="text-xs font-medium mt-1">${p}%</div>`; }
  function getRoleBadge(r) { let icons = { admin: '<i class="fas fa-crown"></i>', editor: '<i class="fas fa-edit"></i>', viewer: '<i class="fas fa-eye"></i>' }; return `<span class="permission-badge">${icons[r] || icons.viewer} ${r.toUpperCase()}</span>`; }

  function renderCardsAndStats() {
    let filtered = getFiltered(), total = employeesData.length, avgProfile = Math.round(employeesData.reduce((a, b) => a + b.profile, 0) / total);
    let avgSalary = Math.round(employeesData.reduce((a, b) => a + (b.salary || 0), 0) / total);
    document.getElementById("statsCards").innerHTML = `<div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-users text-3xl text-emerald-500"></i><h3 class="text-2xl font-bold mt-2">${total}</h3><p class="text-gray-500">Total workforce</p></div><div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-dollar-sign text-3xl text-blue-500"></i><h3 class="text-2xl font-bold mt-2">$${(avgSalary / 1000).toFixed(0)}k</h3><p>Avg Salary</p></div><div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-chart-line text-3xl text-purple-500"></i><h3 class="text-2xl font-bold mt-2">${avgProfile}%</h3><p>Avg Profile</p></div><div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-medal text-3xl text-yellow-500"></i><h3 class="text-2xl font-bold mt-2">${employeesData.filter(e => e.profile >= 80).length}</h3><p>High performers</p></div>`;
    let low = employeesData.filter(e => e.profile < 40).length, mid = employeesData.filter(e => e.profile >= 40 && e.profile < 70).length, high = employeesData.filter(e => e.profile >= 70).length, tot = employeesData.length;
    document.getElementById("profileDistChart").innerHTML = `<div class="mb-2"><i class="fas fa-chart-line text-red-500 mr-2"></i>Low: ${low} (${Math.round(low / tot * 100)}%)<div class="progress mt-1 h-1"><div class="progress-bar bg-red-500" style="width:${low / tot * 100}%"></div></div></div><div class="mb-2"><i class="fas fa-chart-line text-yellow-500 mr-2"></i>Medium: ${mid} (${Math.round(mid / tot * 100)}%)<div class="progress mt-1 h-1"><div class="progress-bar bg-yellow-500" style="width:${mid / tot * 100}%"></div></div></div><div><i class="fas fa-chart-line text-green-500 mr-2"></i>High: ${high} (${Math.round(high / tot * 100)}%)<div class="progress mt-1 h-1"><div class="progress-bar bg-green-500" style="width:${high / tot * 100}%"></div></div></div>`;
    let deptMap = new Map(); employeesData.forEach(e => deptMap.set(e.department, (deptMap.get(e.department) || 0) + 1));
    document.getElementById("deptChart").innerHTML = Array.from(deptMap.entries()).map(([dept, count]) => `<div class="flex justify-between mb-1"><span><i class="fas fa-building mr-2"></i>${dept}</span><span class="badge bg-secondary">${count}</span></div><div class="progress mb-2 h-1"><div class="progress-bar bg-info" style="width:${count / tot * 100}%"></div></div>`).join('');
  }


