
(function () {
  let employeesData = [
    { id: "0001", name: "Anika Vaccaro", designation: "Manager", department: "Operations", team: "Super A", supervisor: "Kaylo Margo", tenure: "1 Yr, 2 Mo", profile: 95, shift: "Morning", city: "New York", salary: 85000, avatar: "https://randomuser.me/api/portraits/women/68.jpg", role: "admin" },
    { id: "0002", name: "Chance Stanton", designation: "Department Head", department: "HR", team: "Super B", supervisor: "Ayson Westervelt", tenure: "3 Yr, 6 Mo", profile: 45, shift: "Evening", city: "Austin", salary: 75000, avatar: "https://randomuser.me/api/portraits/men/32.jpg", role: "editor" },
    { id: "0003", name: "Gretchen Lubin", designation: "Team Lead", department: "Operations", team: "Super C", supervisor: "Ryan Vaccaro", tenure: "2 Yr", profile: 90, shift: "Morning", city: "Seattle", salary: 72000, avatar: "https://randomuser.me/api/portraits/women/44.jpg", role: "editor" },
    { id: "0004", name: "Roger Westervelt", designation: "VOB Specialist", department: "Operations", team: "Super D", supervisor: "Anika Gold", tenure: "1 Yr, 2 Mo", profile: 93, shift: "Night", city: "Chicago", salary: 65000, avatar: "https://randomuser.me/api/portraits/men/45.jpg", role: "viewer" },
    { id: "0005", name: "Tatiana Dias", designation: "Account Manager", department: "Operations", team: "Super E", supervisor: "Angel Levin", tenure: "1 Yr, 1 Mo", profile: 15, shift: "Morning", city: "Miami", salary: 68000, avatar: "https://randomuser.me/api/portraits/women/29.jpg", role: "viewer" },
    { id: "0006", name: "Marcus Chen", designation: "Senior Analyst", department: "Finance", team: "Alpha", supervisor: "Linda Wu", tenure: "2 Yr, 4 Mo", profile: 88, shift: "Morning", city: "San Francisco", salary: 82000, avatar: "https://randomuser.me/api/portraits/men/22.jpg", role: "editor" },
    { id: "0007", name: "Sophia Rodriguez", designation: "HR Generalist", department: "HR", team: "Talent Squad", supervisor: "Chance Stanton", tenure: "1 Yr", profile: 72, shift: "Evening", city: "Los Angeles", salary: 62000, avatar: "https://randomuser.me/api/portraits/women/90.jpg", role: "viewer" },
    { id: "0008", name: "James Okafor", designation: "IT Support", department: "Technology", team: "TechOps", supervisor: "Rita Blake", tenure: "6 Mo", profile: 60, shift: "Night", city: "Houston", salary: 58000, avatar: "https://randomuser.me/api/portraits/men/55.jpg", role: "viewer" },
    { id: "0009", name: "Elena Park", designation: "Product Owner", department: "Product", team: "Innovate", supervisor: "Marcus Chen", tenure: "8 Mo", profile: 82, shift: "Morning", city: "Seattle", salary: 90000, avatar: "https://randomuser.me/api/portraits/women/12.jpg", role: "editor" }
  ];
  let auditLog = [], currentFilters = { jobTitle: "", department: "", team: "", city: "" };
  let employeeModalInstance = null, permissionsModalInstance = null, isEditMode = false;

  function addLog(action, details) { auditLog.unshift({ timestamp: new Date().toLocaleString(), action, details }); if (auditLog.length > 20) auditLog.pop(); }
  function getFiltered() { return employeesData.filter(e => (!currentFilters.jobTitle || e.designation.toLowerCase().includes(currentFilters.jobTitle.toLowerCase())) && (!currentFilters.department || e.department.toLowerCase().includes(currentFilters.department.toLowerCase())) && (!currentFilters.team || e.team.toLowerCase().includes(currentFilters.team.toLowerCase())) && (!currentFilters.city || e.city.toLowerCase().includes(currentFilters.city.toLowerCase()))); }
  function profileClass(p) { return p < 40 ? "low" : p < 70 ? "medium" : "high"; }
  function renderProfile(p) { let cls = profileClass(p); return `<div class="profile-bar ${cls}"><div class="bar-fill" style="width:${p}%"></div></div><div class="text-xs font-medium mt-1">${p}%</div>`; }
  function getRoleBadge(r) { const icons = { admin: '<i class="fas fa-crown"></i>', editor: '<i class="fas fa-edit"></i>', viewer: '<i class="fas fa-eye"></i>' }; return `<span class="permission-badge">${icons[r] || icons.viewer} ${r.toUpperCase()}</span>`; }

  function renderCardsAndStats() {
    const filtered = getFiltered(), total = employeesData.length, avgProfile = Math.round(employeesData.reduce((a, b) => a + b.profile, 0) / total);
    const avgSalary = Math.round(employeesData.reduce((a, b) => a + (b.salary || 0), 0) / total);
    document.getElementById("statsCards").innerHTML = `<div class="bg-white p-5 rounded-2xl shadow-sm border"><div class="flex justify-between"><i class="fas fa-users text-3xl text-emerald-500"></i></div><h3 class="text-2xl font-bold mt-2">${total}</h3><p class="text-gray-500">Total workforce</p><span class="text-xs text-green-600"><i class="fas fa-arrow-up"></i> +12%</span></div><div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-dollar-sign text-3xl text-blue-500"></i><h3 class="text-2xl font-bold mt-2">$${(avgSalary / 1000).toFixed(0)}k</h3><p>Avg Salary</p></div><div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-chart-line text-3xl text-purple-500"></i><h3 class="text-2xl font-bold mt-2">${avgProfile}%</h3><p>Avg Profile</p></div><div class="bg-white p-5 rounded-2xl shadow-sm border"><i class="fas fa-medal text-3xl text-yellow-500"></i><h3 class="text-2xl font-bold mt-2">${employeesData.filter(e => e.profile >= 80).length}</h3><p>High performers</p></div>`;
    const low = employeesData.filter(e => e.profile < 40).length, mid = employeesData.filter(e => e.profile >= 40 && e.profile < 70).length, high = employeesData.filter(e => e.profile >= 70).length, tot = employeesData.length;
    document.getElementById("profileDistChart").innerHTML = `<div class="mb-2"><span class="text-red-500">●</span> Low: ${low} (${Math.round(low / tot * 100)}%)<div class="progress mt-1 h-1"><div class="progress-bar bg-red-500" style="width:${low / tot * 100}%"></div></div></div><div class="mb-2"><span class="text-yellow-500">●</span> Medium: ${mid} (${Math.round(mid / tot * 100)}%)<div class="progress mt-1 h-1"><div class="progress-bar bg-yellow-500" style="width:${mid / tot * 100}%"></div></div></div><div><span class="text-green-500">●</span> High: ${high} (${Math.round(high / tot * 100)}%)<div class="progress mt-1 h-1"><div class="progress-bar bg-green-500" style="width:${high / tot * 100}%"></div></div></div>`;
    const deptMap = new Map(); employeesData.forEach(e => deptMap.set(e.department, (deptMap.get(e.department) || 0) + 1));
    document.getElementById("deptChart").innerHTML = Array.from(deptMap.entries()).map(([dept, count]) => `<div class="flex justify-between mb-1"><span>${dept}</span><span class="badge bg-secondary">${count}</span></div><div class="progress mb-2 h-1"><div class="progress-bar bg-info" style="width:${count / tot * 100}%"></div></div>`).join('');
  }

  function renderTables() {
    const filtered = getFiltered(); renderCardsAndStats();
    document.getElementById("dashboardTableBody").innerHTML = filtered.map(e => `<tr><td>${e.id}</td><td><img src="${e.avatar}" class="avatar"> ${e.name}</td><td>${e.designation}</td><td><span class="badge bg-light">${e.department}</span></td><td>${e.team}</td><td>${e.supervisor}</td><td><i class="far fa-calendar-alt mr-1"></i>${e.tenure}</td><td>${renderProfile(e.profile)}</td></tr>`).join("");
    document.getElementById("usersTableBody").innerHTML = filtered.map(e => `<tr><td>${e.id}</td><td><img src="${e.avatar}" class="avatar"> ${e.name}</td><td>${e.designation}</td><td>${e.department}</td><td>${e.team}</td><td>${e.supervisor}</td><td>${e.tenure}</td><td>${renderProfile(e.profile)}</td><td>${getRoleBadge(e.role)}</td><td class="action-icons"><i class="fas fa-edit text-primary" onclick="app.editEmployee('${e.id}')"></i> <i class="fas fa-trash-alt text-danger" onclick="app.deleteEmployee('${e.id}')"></i> <i class="fas fa-shield-alt" onclick="app.openPermissionsForUser('${e.id}')"></i></td></tr>`).join("");
  }

  function genId() { let max = 0; employeesData.forEach(e => { let n = parseInt(e.id); if (!isNaN(n) && n > max) max = n; }); return String(max + 1).padStart(4, '0'); }
  function openModal(id = null) { isEditMode = !!id; document.getElementById("modalTitle").innerHTML = isEditMode ? '<i class="fas fa-pen"></i> Edit' : '<i class="fas fa-plus"></i> Add'; if (id) { let emp = employeesData.find(e => e.id === id); if (emp) Object.keys(emp).forEach(k => { let el = document.getElementById(`emp${k.charAt(0).toUpperCase() + k.slice(1)}`); if (el) el.value = emp[k]; }); } else { document.getElementById("empId").value = genId();["empName", "empDesignation", "empDepartment", "empTeam", "empSupervisor", "empTenure", "empShift", "empCity", "empAvatar"].forEach(i => { let el = document.getElementById(i); if (el) el.value = ""; }); document.getElementById("empProfile").value = 50; document.getElementById("empAvatar").value = "https://randomuser.me/api/portraits/lego/1.jpg"; } employeeModalInstance.show(); }
  function saveEmployee() { let id = document.getElementById("empId").value, name = document.getElementById("empName").value.trim(); if (!name) { alert("Name required"); return; } let profile = parseInt(document.getElementById("empProfile").value); if (isNaN(profile) || profile < 0 || profile > 100) { alert("Profile 0-100"); return; } let newEmp = { id, name, profile, role: isEditMode ? employeesData.find(e => e.id === id)?.role || "viewer" : "viewer", designation: document.getElementById("empDesignation").value.trim() || "Staff", department: document.getElementById("empDepartment").value.trim() || "General", team: document.getElementById("empTeam").value.trim() || "Core", supervisor: document.getElementById("empSupervisor").value.trim() || "Admin", tenure: document.getElementById("empTenure").value.trim() || "0 Yr", shift: document.getElementById("empShift").value.trim() || "Morning", city: document.getElementById("empCity").value.trim() || "Unknown", salary: 65000, avatar: document.getElementById("empAvatar").value.trim() || "https://randomuser.me/api/portraits/lego/1.jpg" }; if (isEditMode) { let idx = employeesData.findIndex(e => e.id === id); if (idx !== -1) employeesData[idx] = newEmp; addLog("UPDATE", `${name} updated`); } else { if (employeesData.some(e => e.id === id)) { alert("Duplicate ID"); return; } employeesData.push(newEmp); addLog("CREATE", `${name} added`); } renderTables(); employeeModalInstance.hide(); showToast(`✅ ${isEditMode ? 'Updated' : 'Added'} ${name}`); }
  function deleteEmployee(id) { let emp = employeesData.find(e => e.id === id); if (confirm(`Delete ${emp?.name}?`)) { employeesData = employeesData.filter(e => e.id !== id); addLog("DELETE", `${emp?.name} removed`); renderTables(); showToast(`🗑️ Deleted ${emp?.name}`); } }
  function assignRoleToUser() { let empId = document.getElementById("assignRoleEmpId").value.trim(), newRole = document.getElementById("assignRoleSelect").value, emp = employeesData.find(e => e.id === empId); if (!emp) { alert("ID not found"); return; } emp.role = newRole; addLog("PERMISSION", `${emp.name} → ${newRole}`); renderTables(); showToast(`🔒 ${emp.name} now ${newRole}`); document.getElementById("assignRoleEmpId").value = ""; if (permissionsModalInstance) permissionsModalInstance.hide(); }
  function openPermissionsModalGlobal() { renderPermissionsList(); permissionsModalInstance.show(); }
  function renderPermissionsList() { document.getElementById("permissionsList").innerHTML = employeesData.map(e => `<div class="flex justify-between items-center border-b py-2"><span><strong>${e.name}</strong> (${e.id})</span><div>${getRoleBadge(e.role)} <button class="btn btn-sm btn-outline-secondary" onclick="app.assignRoleToId('${e.id}','editor')">Editor</button> <button class="btn btn-sm btn-outline-primary" onclick="app.assignRoleToId('${e.id}','admin')">Admin</button></div></div>`).join(''); }
  function assignRoleToId(empId, role) { let emp = employeesData.find(e => e.id === empId); if (emp) { emp.role = role; addLog("PERMISSION", `${emp.name} → ${role}`); renderTables(); renderPermissionsList(); showToast(`🛡️ ${emp.name} now ${role}`); } }
  function showToast(msg) { let t = document.createElement("div"); t.className = "toast-notify"; t.innerHTML = `<i class="fas fa-info-circle mr-2"></i>${msg}`; document.body.appendChild(t); setTimeout(() => t.remove(), 2500); }
  function exportCSV() { let filtered = getFiltered(); let headers = ["ID", "Name", "Designation", "Dept", "Team", "Supervisor", "Tenure", "Profile%", "Shift", "City", "Role"]; let rows = filtered.map(e => [e.id, e.name, e.designation, e.department, e.team, e.supervisor, e.tenure, e.profile, e.shift, e.city, e.role]); let csv = [headers, ...rows].map(r => r.join(",")).join("\n"); let blob = new Blob([csv], { type: "text/csv" }); let a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "employees.csv"; a.click(); showToast("Export complete"); }
  function applyFilters() { currentFilters = { jobTitle: document.getElementById("filterJobTitle").value.trim(), department: document.getElementById("filterDepartment").value.trim(), team: document.getElementById("filterTeam").value.trim(), city: document.getElementById("filterCity").value.trim() }; renderTables(); app.closeFilterSidebar(); showToast("Filters applied"); }
  function resetFilters() { ["filterJobTitle", "filterDepartment", "filterTeam", "filterCity"].forEach(id => document.getElementById(id).value = ""); currentFilters = { jobTitle: "", department: "", team: "", city: "" }; renderTables(); showToast("Filters reset"); }
  function openFilterSidebar() { document.getElementById("filterSidebar").classList.add("translate-x-0"); document.getElementById("filterSidebar").classList.remove("translate-x-full"); }
  function closeFilterSidebar() { document.getElementById("filterSidebar").classList.add("translate-x-full"); document.getElementById("filterSidebar").classList.remove("translate-x-0"); }
  function openPermissionsForUser(id) { openPermissionsModalGlobal(); setTimeout(() => { document.getElementById("assignRoleEmpId").value = id; }, 100); }
  function showHRReport() { showToast(`📊 HR Report: ${employeesData.length} employees | Avg Salary: $${Math.round(employeesData.reduce((a, b) => a + (b.salary || 0), 0) / employeesData.length).toLocaleString()}`); }
  function showRetentionChart() { showToast("📈 Retention Rate: 94% · Above industry benchmark"); }
  function showDepartmentStats() { let ops = employeesData.filter(e => e.department === "Operations").length; showToast(`🏢 Top Dept: Operations (${ops} employees)`); }
  function showSalaryInsights() { let avg = Math.round(employeesData.reduce((a, b) => a + (b.salary || 0), 0) / employeesData.length); showToast(`💰 Salary Range: $58k–$90k · Average: $${avg.toLocaleString()}`); }
  function showAuditLog() { alert("📋 Audit Log (last 8):\n" + auditLog.slice(0, 8).map(l => `${l.timestamp} - ${l.action}: ${l.details}`).join("\n") || "No actions"); }
  function showHelp() { alert("📘 NexusHR Guide\n• Add/Edit/Delete employees\n• Dark mode toggle (top right)\n• Filter sidebar for refining\n• Role permissions: Admin, Editor, Viewer\n• Export CSV & Audit trail\n• Fully responsive design"); }
  window.app = { showSection(s) { document.getElementById("dashboardSection").style.display = s === "dashboard" ? "block" : "none"; document.getElementById("usersSection").style.display = s === "users" ? "block" : "none"; renderTables(); if (window.innerWidth <= 768) document.getElementById("sidebar").classList.remove("open"); document.getElementById("mobileOverlay").classList.remove("active"); }, toggleDropdown(m) { let menu = document.getElementById(m); if (!menu) return; let vis = menu.style.display === "block"; document.querySelectorAll(".submenu").forEach(s => s.style.display = "none"); if (!vis) menu.style.display = "block"; }, openFilterSidebar, closeFilterSidebar, alertFeature: (msg) => showToast(`✨ ${msg}`), openEmployeeModal: () => openModal(), editEmployee: (id) => openModal(id), deleteEmployee, exportToCSV, openPermissionsModal: () => openPermissionsModalGlobal(), openPermissionsForUser, assignRole: () => assignRoleToUser(), assignRoleToId, showAuditLog, showHelp, openHRReport: showHRReport, showRetentionChart, showDepartmentStats, showSalaryInsights };

  function toggleSidebarMobile() { let s = document.getElementById("sidebar"); s.classList.toggle("open"); document.getElementById("mobileOverlay").classList.toggle("active"); }
  function closeSidebar() { document.getElementById("sidebar").classList.remove("open"); document.getElementById("mobileOverlay").classList.remove("active"); }
  document.getElementById("mobileMenuBtn")?.addEventListener("click", toggleSidebarMobile);
  document.getElementById("themeToggle")?.addEventListener("click", () => { document.body.classList.toggle("dark"); localStorage.setItem("theme", document.body.classList.contains("dark") ? "dark" : "light"); const icon = document.querySelector("#themeToggle i"); if (document.body.classList.contains("dark")) icon.className = "fas fa-sun"; else icon.className = "fas fa-moon"; showToast(document.body.classList.contains("dark") ? "🌙 Dark mode" : "☀️ Light mode"); });
  if (localStorage.getItem("theme") === "dark") document.body.classList.add("dark");

  document.getElementById("applyFilterBtn").addEventListener("click", applyFilters);
  document.getElementById("resetFilterBtn").addEventListener("click", () => { resetFilters(); closeFilterSidebar(); });
  document.getElementById("saveEmployeeBtn").addEventListener("click", saveEmployee);
  employeeModalInstance = new bootstrap.Modal(document.getElementById("employeeModal"));
  permissionsModalInstance = new bootstrap.Modal(document.getElementById("permissionsModal"));
  renderTables(); app.showSection("dashboard");
})();
